@RecipesAPI_HostAddress = http://localhost:5202/recipes-api

###

GET {{RecipesAPI_HostAddress}}/recipes?pageIndex=0&pageSize=10
Accept: application/problem+json

###

GET {{RecipesAPI_HostAddress}}/recipes/2
Accept: application/problem+json

###

POST {{RecipesAPI_HostAddress}}/recipes
Accept: application/problem+json
Content-Type: application/json

{
  "id": 11,
  "title": "MyTitle2"
}

###